version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course_administration
    volumes:
       - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"